"""Core business logic for Deposition Summarizer.

Provides comprehensive deposition transcript analysis including:
- Full deposition summary
- Key admission extraction
- Contradiction detection
- Important testimony extraction
- Follow-up question generation
- Timeline construction

All processing uses local Gemma 4 via Ollama — zero data leaves the machine.
"""

import json
import logging
import re
import sys
import os
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from common.llm_client import chat, check_ollama_running

from .config import load_config

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Legal Disclaimer
# ---------------------------------------------------------------------------

LEGAL_DISCLAIMER = """
╔══════════════════════════════════════════════════════════════════════════════╗
║                           LEGAL DISCLAIMER                                 ║
╠══════════════════════════════════════════════════════════════════════════════╣
║                                                                            ║
║  This tool is designed to ASSIST legal professionals in reviewing           ║
║  deposition transcripts. It is NOT a substitute for professional legal      ║
║  judgment.                                                                  ║
║                                                                            ║
║  • All analysis is generated by AI and must be verified by a licensed       ║
║    attorney before use in any legal proceeding.                             ║
║  • This tool does NOT provide legal advice.                                 ║
║  • AI-generated summaries may contain inaccuracies or miss critical         ║
║    nuances in testimony.                                                    ║
║  • Always cross-reference AI output against the original transcript.        ║
║  • 100% LOCAL processing — no data leaves your machine.                     ║
║  • Attorney-client privilege is maintained through local-only processing.   ║
║                                                                            ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""

# ---------------------------------------------------------------------------
# System Prompt
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """You are an expert legal analyst specializing in deposition transcript analysis.
You have extensive experience reviewing depositions for litigation support.

Your role is to carefully analyze deposition transcripts and extract structured information.
You must be precise, thorough, and objective in your analysis.

Key responsibilities:
1. Identify key admissions — statements by the deponent that support or undermine a party's position.
2. Detect contradictions — inconsistencies between statements within the deposition or with known facts.
3. Extract important testimony — significant statements that could impact the case.
4. Build witness profiles — assess credibility, demeanor, and reliability indicators.
5. Generate follow-up questions — identify areas needing further exploration.
6. Construct timelines — extract chronological events referenced in testimony.

Always provide page/line references when available. Be objective and note both favorable
and unfavorable testimony. Flag areas of uncertainty. Use plain language to explain
legal significance."""

# ---------------------------------------------------------------------------
# Data Classes
# ---------------------------------------------------------------------------


@dataclass
class KeyAdmission:
    """A key admission made during deposition testimony."""
    speaker: str
    statement: str
    page_line: str = ""
    significance: str = "medium"  # low, medium, high, critical


@dataclass
class Contradiction:
    """A contradiction detected between two statements in the deposition."""
    statement_a: str
    statement_b: str
    page_line_a: str = ""
    page_line_b: str = ""
    explanation: str = ""


@dataclass
class ImportantTestimony:
    """A piece of important testimony extracted from the deposition."""
    speaker: str
    topic: str
    summary: str
    page_line: str = ""
    relevance: str = "medium"  # low, medium, high, critical


@dataclass
class WitnessProfile:
    """Profile of a deposition witness."""
    name: str = ""
    role: str = ""
    credibility_notes: List[str] = field(default_factory=list)
    demeanor_notes: List[str] = field(default_factory=list)


@dataclass
class DepositionSummary:
    """Complete summary of a deposition transcript."""
    title: str = ""
    witness: str = ""
    date: str = ""
    duration: str = ""
    overall_summary: str = ""
    key_admissions: List[KeyAdmission] = field(default_factory=list)
    contradictions: List[Contradiction] = field(default_factory=list)
    important_testimony: List[ImportantTestimony] = field(default_factory=list)
    witness_profile: WitnessProfile = field(default_factory=WitnessProfile)
    topics_covered: List[str] = field(default_factory=list)
    follow_up_questions: List[str] = field(default_factory=list)
    timeline: List[Dict[str, str]] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Display Helpers
# ---------------------------------------------------------------------------

def get_significance_color(significance: str) -> str:
    """Return a Rich color string for the given significance level."""
    colors = {
        "low": "green",
        "medium": "yellow",
        "high": "red",
        "critical": "bold red",
    }
    return colors.get(significance.lower(), "white")


def get_significance_emoji(significance: str) -> str:
    """Return an emoji for the given significance level."""
    emojis = {
        "low": "🟢",
        "medium": "🟡",
        "high": "🔴",
        "critical": "🚨",
    }
    return emojis.get(significance.lower(), "⚪")


# ---------------------------------------------------------------------------
# JSON Parsing Helper
# ---------------------------------------------------------------------------

def _parse_json_response(text: str) -> Any:
    """Parse JSON from LLM response, handling code blocks and malformed output.

    Args:
        text: Raw LLM response text.

    Returns:
        Parsed JSON object (dict or list).

    Raises:
        ValueError: If no valid JSON can be extracted.
    """
    # Try direct parse first
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Try extracting from markdown code blocks
    patterns = [
        r'```json\s*\n?(.*?)\n?\s*```',
        r'```\s*\n?(.*?)\n?\s*```',
    ]
    for pattern in patterns:
        match = re.search(pattern, text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group(1).strip())
            except json.JSONDecodeError:
                continue

    # Try finding JSON array or object in the text
    for start_char, end_char in [('[', ']'), ('{', '}')]:
        start = text.find(start_char)
        end = text.rfind(end_char)
        if start != -1 and end != -1 and end > start:
            try:
                return json.loads(text[start:end + 1])
            except json.JSONDecodeError:
                continue

    raise ValueError(f"Could not parse JSON from response: {text[:200]}...")


# ---------------------------------------------------------------------------
# Core Analysis Functions
# ---------------------------------------------------------------------------

def summarize_deposition(transcript: str, model: str = "gemma4:latest") -> DepositionSummary:
    """Generate a comprehensive summary of a deposition transcript.

    Args:
        transcript: The full deposition transcript text.
        model: LLM model name to use.

    Returns:
        A DepositionSummary with all analysis fields populated.
    """
    logger.info("Summarizing deposition: %d chars", len(transcript))
    cfg = load_config()
    max_len = cfg.get("analysis", {}).get("max_transcript_length", 50000)
    if len(transcript) > max_len:
        transcript = transcript[:max_len] + "\n\n[... transcript truncated ...]"

    prompt = f"""Analyze the following deposition transcript and provide a comprehensive summary.

Return your analysis as JSON with this exact structure:
{{
    "title": "Brief title for this deposition",
    "witness": "Name of the deponent/witness",
    "date": "Date of deposition if mentioned",
    "duration": "Duration if mentioned",
    "overall_summary": "2-3 paragraph comprehensive summary",
    "key_admissions": [
        {{"speaker": "name", "statement": "the admission", "page_line": "p.X, ln.Y", "significance": "high"}}
    ],
    "contradictions": [
        {{"statement_a": "first statement", "statement_b": "contradicting statement", "page_line_a": "p.X", "page_line_b": "p.Y", "explanation": "why these contradict"}}
    ],
    "important_testimony": [
        {{"speaker": "name", "topic": "topic", "summary": "summary of testimony", "page_line": "p.X", "relevance": "high"}}
    ],
    "witness_profile": {{
        "name": "witness name",
        "role": "their role",
        "credibility_notes": ["note1", "note2"],
        "demeanor_notes": ["note1"]
    }},
    "topics_covered": ["topic1", "topic2"],
    "follow_up_questions": ["question1", "question2"],
    "timeline": [
        {{"date": "date", "event": "what happened"}}
    ]
}}

DEPOSITION TRANSCRIPT:
{transcript}"""

    messages = [{"role": "user", "content": prompt}]
    response = chat(
        messages=messages,
        model=model,
        system_prompt=SYSTEM_PROMPT,
        temperature=cfg["llm"]["temperature"],
        max_tokens=cfg["llm"]["max_tokens"],
    )

    try:
        data = _parse_json_response(response)
    except ValueError:
        logger.warning("Failed to parse structured response, returning raw summary")
        return DepositionSummary(overall_summary=response)

    summary = DepositionSummary(
        title=data.get("title", ""),
        witness=data.get("witness", ""),
        date=data.get("date", ""),
        duration=data.get("duration", ""),
        overall_summary=data.get("overall_summary", ""),
        topics_covered=data.get("topics_covered", []),
        follow_up_questions=data.get("follow_up_questions", []),
    )

    for adm in data.get("key_admissions", []):
        summary.key_admissions.append(KeyAdmission(
            speaker=adm.get("speaker", ""),
            statement=adm.get("statement", ""),
            page_line=adm.get("page_line", ""),
            significance=adm.get("significance", "medium"),
        ))

    for con in data.get("contradictions", []):
        summary.contradictions.append(Contradiction(
            statement_a=con.get("statement_a", ""),
            statement_b=con.get("statement_b", ""),
            page_line_a=con.get("page_line_a", ""),
            page_line_b=con.get("page_line_b", ""),
            explanation=con.get("explanation", ""),
        ))

    for test in data.get("important_testimony", []):
        summary.important_testimony.append(ImportantTestimony(
            speaker=test.get("speaker", ""),
            topic=test.get("topic", ""),
            summary=test.get("summary", ""),
            page_line=test.get("page_line", ""),
            relevance=test.get("relevance", "medium"),
        ))

    wp = data.get("witness_profile", {})
    summary.witness_profile = WitnessProfile(
        name=wp.get("name", ""),
        role=wp.get("role", ""),
        credibility_notes=wp.get("credibility_notes", []),
        demeanor_notes=wp.get("demeanor_notes", []),
    )

    for tl in data.get("timeline", []):
        summary.timeline.append({"date": tl.get("date", ""), "event": tl.get("event", "")})

    return summary


def find_admissions(transcript: str, model: str = "gemma4:latest") -> List[KeyAdmission]:
    """Extract key admissions from a deposition transcript.

    Args:
        transcript: The deposition transcript text.
        model: LLM model name.

    Returns:
        List of KeyAdmission objects.
    """
    logger.info("Finding admissions in transcript: %d chars", len(transcript))
    cfg = load_config()

    prompt = f"""Analyze this deposition transcript and identify all KEY ADMISSIONS.

A key admission is a statement where the witness:
- Acknowledges facts unfavorable to their position
- Confirms liability or fault
- Admits to knowledge they previously denied
- Concedes a point that strengthens the opposing party's case

Return as JSON array:
[
    {{
        "speaker": "witness name",
        "statement": "exact or near-exact quote of the admission",
        "page_line": "page and line reference if available",
        "significance": "low|medium|high|critical"
    }}
]

DEPOSITION TRANSCRIPT:
{transcript}"""

    messages = [{"role": "user", "content": prompt}]
    response = chat(
        messages=messages,
        model=model,
        system_prompt=SYSTEM_PROMPT,
        temperature=cfg["llm"]["temperature"],
        max_tokens=cfg["llm"]["max_tokens"],
    )

    try:
        data = _parse_json_response(response)
    except ValueError:
        logger.warning("Failed to parse admissions response")
        return []

    if isinstance(data, dict):
        data = data.get("admissions", data.get("key_admissions", []))

    return [
        KeyAdmission(
            speaker=item.get("speaker", ""),
            statement=item.get("statement", ""),
            page_line=item.get("page_line", ""),
            significance=item.get("significance", "medium"),
        )
        for item in data
        if isinstance(item, dict)
    ]


def find_contradictions(transcript: str, model: str = "gemma4:latest") -> List[Contradiction]:
    """Find contradictions within a deposition transcript.

    Args:
        transcript: The deposition transcript text.
        model: LLM model name.

    Returns:
        List of Contradiction objects.
    """
    logger.info("Finding contradictions in transcript: %d chars", len(transcript))
    cfg = load_config()

    prompt = f"""Analyze this deposition transcript and identify all CONTRADICTIONS.

Look for:
- Statements that directly contradict each other within the deposition
- Inconsistencies in the witness's account of events
- Changes in testimony about dates, times, locations, or people involved
- Conflicting descriptions of the same event

Return as JSON array:
[
    {{
        "statement_a": "first statement (quote or paraphrase)",
        "statement_b": "contradicting statement (quote or paraphrase)",
        "page_line_a": "reference for statement A",
        "page_line_b": "reference for statement B",
        "explanation": "why these statements contradict each other"
    }}
]

DEPOSITION TRANSCRIPT:
{transcript}"""

    messages = [{"role": "user", "content": prompt}]
    response = chat(
        messages=messages,
        model=model,
        system_prompt=SYSTEM_PROMPT,
        temperature=cfg["llm"]["temperature"],
        max_tokens=cfg["llm"]["max_tokens"],
    )

    try:
        data = _parse_json_response(response)
    except ValueError:
        logger.warning("Failed to parse contradictions response")
        return []

    if isinstance(data, dict):
        data = data.get("contradictions", [])

    return [
        Contradiction(
            statement_a=item.get("statement_a", ""),
            statement_b=item.get("statement_b", ""),
            page_line_a=item.get("page_line_a", ""),
            page_line_b=item.get("page_line_b", ""),
            explanation=item.get("explanation", ""),
        )
        for item in data
        if isinstance(item, dict)
    ]


def extract_testimony(
    transcript: str, topic: str, model: str = "gemma4:latest"
) -> List[ImportantTestimony]:
    """Extract testimony related to a specific topic from the deposition.

    Args:
        transcript: The deposition transcript text.
        topic: The topic to search for in testimony.
        model: LLM model name.

    Returns:
        List of ImportantTestimony objects related to the topic.
    """
    logger.info("Extracting testimony on '%s': %d chars", topic, len(transcript))
    cfg = load_config()

    prompt = f"""Analyze this deposition transcript and extract all testimony related to the topic: "{topic}"

For each relevant piece of testimony, provide:
- Who said it
- A summary of what was said
- The page/line reference if available
- The relevance level (low, medium, high, critical)

Return as JSON array:
[
    {{
        "speaker": "name of the speaker",
        "topic": "{topic}",
        "summary": "summary of the testimony on this topic",
        "page_line": "page and line reference",
        "relevance": "low|medium|high|critical"
    }}
]

DEPOSITION TRANSCRIPT:
{transcript}"""

    messages = [{"role": "user", "content": prompt}]
    response = chat(
        messages=messages,
        model=model,
        system_prompt=SYSTEM_PROMPT,
        temperature=cfg["llm"]["temperature"],
        max_tokens=cfg["llm"]["max_tokens"],
    )

    try:
        data = _parse_json_response(response)
    except ValueError:
        logger.warning("Failed to parse testimony response")
        return []

    if isinstance(data, dict):
        data = data.get("testimony", data.get("important_testimony", []))

    return [
        ImportantTestimony(
            speaker=item.get("speaker", ""),
            topic=item.get("topic", topic),
            summary=item.get("summary", ""),
            page_line=item.get("page_line", ""),
            relevance=item.get("relevance", "medium"),
        )
        for item in data
        if isinstance(item, dict)
    ]


def generate_follow_up_questions(
    transcript: str, model: str = "gemma4:latest"
) -> List[str]:
    """Generate suggested follow-up questions based on the deposition transcript.

    Args:
        transcript: The deposition transcript text.
        model: LLM model name.

    Returns:
        List of follow-up question strings.
    """
    logger.info("Generating follow-up questions: %d chars", len(transcript))
    cfg = load_config()

    prompt = f"""Based on this deposition transcript, suggest follow-up questions that an attorney should ask.

Focus on:
- Gaps in testimony that need clarification
- Vague or evasive answers that should be pinned down
- Areas where the witness seemed uncertain or contradictory
- Topics that were mentioned but not fully explored
- Potential impeachment opportunities
- Foundation questions for key exhibits

Return as JSON array of strings:
["Question 1?", "Question 2?", "Question 3?"]

DEPOSITION TRANSCRIPT:
{transcript}"""

    messages = [{"role": "user", "content": prompt}]
    response = chat(
        messages=messages,
        model=model,
        system_prompt=SYSTEM_PROMPT,
        temperature=cfg["llm"]["temperature"],
        max_tokens=cfg["llm"]["max_tokens"],
    )

    try:
        data = _parse_json_response(response)
    except ValueError:
        logger.warning("Failed to parse follow-up questions response")
        return []

    if isinstance(data, dict):
        data = data.get("questions", data.get("follow_up_questions", []))

    return [q for q in data if isinstance(q, str)]


def build_timeline(transcript: str, model: str = "gemma4:latest") -> List[Dict[str, str]]:
    """Extract a chronological timeline of events from the deposition.

    Args:
        transcript: The deposition transcript text.
        model: LLM model name.

    Returns:
        List of dicts with 'date' and 'event' keys.
    """
    logger.info("Building timeline from transcript: %d chars", len(transcript))
    cfg = load_config()

    prompt = f"""Analyze this deposition transcript and extract a chronological timeline of events.

Include:
- Specific dates mentioned in testimony
- Relative time references ("two weeks before the incident")
- Sequence of events as described by the witness
- Key milestones or turning points

Return as JSON array sorted chronologically:
[
    {{"date": "date or time reference", "event": "description of what happened"}}
]

DEPOSITION TRANSCRIPT:
{transcript}"""

    messages = [{"role": "user", "content": prompt}]
    response = chat(
        messages=messages,
        model=model,
        system_prompt=SYSTEM_PROMPT,
        temperature=cfg["llm"]["temperature"],
        max_tokens=cfg["llm"]["max_tokens"],
    )

    try:
        data = _parse_json_response(response)
    except ValueError:
        logger.warning("Failed to parse timeline response")
        return []

    if isinstance(data, dict):
        data = data.get("timeline", data.get("events", []))

    return [
        {"date": item.get("date", ""), "event": item.get("event", "")}
        for item in data
        if isinstance(item, dict)
    ]


# ---------------------------------------------------------------------------
# Sample Transcript
# ---------------------------------------------------------------------------

SAMPLE_TRANSCRIPT = """DEPOSITION OF JOHN SMITH
Case No. 2024-CV-4521
Date: March 15, 2024
Location: Law Offices of Thompson & Associates

Page 1, Line 1-25:
Q: Good morning, Mr. Smith. Could you please state your full name for the record?
A: John Michael Smith.

Q: And what is your current position?
A: I am the Director of Operations at Westfield Manufacturing.

Q: How long have you held that position?
A: About four years now. I started in January 2020.

Q: Mr. Smith, were you present at the facility on the evening of September 14, 2023?
A: Yes, I was there until approximately 6:30 PM.

Page 2, Line 1-25:
Q: Can you describe what you observed that evening?
A: It was a normal evening. The third shift was coming in, and I was wrapping up some paperwork in my office.

Q: Did you inspect the equipment on Line 4 that day?
A: I did a walkthrough earlier in the day, around 2 PM.

Q: And what did you observe during that walkthrough?
A: Everything appeared to be operating normally. The pressure gauges were within acceptable ranges.

Q: What are the acceptable ranges for the pressure gauges on Line 4?
A: The operating range is between 150 and 200 PSI. Anything above 250 PSI triggers an automatic shutdown.

Page 3, Line 1-25:
Q: Did you notice any maintenance issues during your walkthrough?
A: Well, I did notice that the safety valve on unit 4B seemed a bit worn. I made a note to have maintenance look at it.

Q: Did you report this to anyone?
A: I mentioned it to Dave Rodriguez, our maintenance supervisor, but I don't recall if I filed a formal work order.

Q: Is it company policy to file a formal work order for safety equipment concerns?
A: Yes, technically it is. But in practice, we often handle minor issues informally.

Q: So you're saying that company safety policies were not always followed?
A: I wouldn't say that exactly. We follow the important ones. The work order system is more of an administrative tool.

Page 4, Line 1-25:
Q: Let me show you Exhibit 7, which is the company safety manual. On page 34, section 5.2, it states — and I quote — "All safety equipment concerns must be documented via formal work order within 24 hours of discovery." Were you aware of this policy?
A: Yes, I was aware of the policy.

Q: But you did not follow it on September 14th?
A: No, I did not file a formal work order that day.

Q: Now, let's talk about the incident itself. When were you first notified about the equipment failure?
A: I received a call from the night shift supervisor, Maria Chen, at approximately 11:45 PM.

Q: What did she tell you?
A: She said there had been a pressure exceedance on Line 4, unit 4B, and that the automatic shutdown had activated. She also said there was some damage to the surrounding equipment.

Page 5, Line 1-25:
Q: Earlier in your testimony, you stated that the pressure gauges were within acceptable ranges at 2 PM. But the incident report — Exhibit 12 — shows pressure readings of 245 PSI at 4:30 PM, just 2.5 hours later. Can you explain this rapid increase?
A: I can't explain the specific increase. I wasn't monitoring the gauges after my walkthrough.

Q: Is a jump from under 200 PSI to 245 PSI in 2.5 hours unusual?
A: It's... it can happen, but it would typically indicate a problem. Either a blockage or a valve malfunction.

Q: The worn safety valve you noticed — could that have been a contributing factor?
A: It's possible. I'm not an engineer, so I can't say definitively.

Q: But you acknowledged the valve appeared worn and you did not file the required work order?
A: That is correct.

Page 6, Line 1-25:
Q: Mr. Smith, in your incident report filed on September 16th — that's Exhibit 14 — you wrote, and I quote, "All equipment was inspected and found to be in satisfactory condition prior to the incident." Is that accurate?
A: That was my assessment at the time of my walkthrough.

Q: But you just testified that you noticed a worn safety valve. Wouldn't that be less than satisfactory?
A: I suppose you could interpret it that way. When I wrote the report, I was referring to the overall condition of the line.

Q: So the report was not entirely accurate?
A: I would say it was accurate in general terms, but perhaps not specific enough regarding the valve.

Q: Let me ask you directly: did you intentionally omit the worn valve from your incident report?
A: No, it was not intentional. In the urgency of the situation, I was focused on the bigger picture.

Page 7, Line 1-25:
Q: How many safety incidents have occurred on Line 4 in the past two years?
A: I believe there have been three, including this one.

Q: And in the two prior incidents, were there also issues with maintenance documentation?
A: I'm not sure. I would need to review the records.

Q: I have the records here — Exhibits 15 and 16. Both prior incidents also had gaps in maintenance documentation. Were you the operations director during those incidents as well?
A: Yes, I was.

Q: So there is a pattern of incomplete safety documentation under your supervision?
A: I wouldn't characterize it that way. We have hundreds of work orders processed correctly. A few gaps don't represent a pattern.

Q: Three incidents in two years with documentation gaps don't represent a pattern?
A: I believe each incident should be evaluated on its own merits.

Q: Mr. Smith, what training have you received on safety compliance?
A: I completed the OSHA 30-hour course when I started the position, and we have annual refresher training.

Q: When was your last refresher training?
A: I believe it was in March 2023. About six months before the incident.
"""
